### PR TITLE
Freebsd ci

### PR DESCRIPTION
**Pull request by olevole**

### CODE REVIEW

**Comment by am11** [comment]
Thanks @olevole! Strangely it looks like at the build step in YAML, the `/etc/skel` directory is not the same, therefore the `npm install` (which invokes clang) gets skipped on i386: https://cirrus-ci.com/task/5116249953533952

```sh
if test "$abi" = "freebsd:11:x86:32"; then
  $execPrefix cd /etc/skel
  $execPrefix ls
fi
.cshrc
.profile
bin
boot
compat
COPYRIGHT
dev
etc
home
lib
libexec
media
mnt
net
proc
rescue
root
sbin
sys
tmp
usr
var
```

**Comment by am11** [comment]
Merged ef36dc270407b3f450a1aa262d5c7cec44b57316.
Still trying to figure out how to do the batching in YAML.

**Comment by am11** [comment]
Since heredoc doesn't work in `.cirrus.yml` (yet?) as does in `.travis.yml` for example, we will need to create a separate file for execution.
Could cbsd support workdir with jexed? Something like: `cbsd jexec workdir=/my/path jail=myjname <command-with-args>`. More generally, it would be also cool to be able to do something like:

```
cbsd jexec jname=j11i386 sh -c "(cd /etc/skel && ls && npm install --unsafe-params)"
```

in a single line.

**Comment by am11** [comment]
Turned out that both heredoc and herestring variants work in normal script, but not from the YAML.
I ended up `echo`ing it like this:

```yaml
  build_script:
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        changeDir="cd /etc/skel &&"
      fi
      echo "$changeDir npm install --unsafe-perm" | $execPrefix /bin/sh
```

Builds are green, trying to furnish desire of publishing binaries to GitHub release artifacts from CI now. 😄

**Comment by am11** [comment]
@olevole, I saw cbsd 12.0.4 has been released, could you tell how long before it will show up at http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/ and http://pkg.freebsd.org/freebsd:11:x86:32/latest/All/?

**Comment by olevole** [comment]
@am11 unfortunately, I don’t know how often these packages are build. Probably during the week. But CBSD 11.0.4 still not in ports tree: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235412

I'm just waiting ;) due to not have ports commit bit

**Pull request closed without merging**
