### PR TITLE
Use <sass_context.h> instead of embedded one

### PR DESCRIPTION
**Pull request by saper**
This is necessary to let node-sass to compile with the unbundled libsass

### CODE REVIEW

**Comment by am11** [comment]
@saper, thanks but I think we should wait for @matryo's changes or perhaps he can pick your commit as is in his PR.
Good stuff is on its way, just hang in there for a bit longer! :sunglasses:

**Comment by saper** [comment]
No problem, I just wanted to push this as a reminder; otherwise the code compiles ok with a bundled libsass only and we wouldn't notice.

**Comment by am11** [comment]
:+1:

**Comment by am11** [comment]
This change was incorporated. Thanks for weighing in!

**Pull request closed without merging**
